# Real-time Whisper Subtitles - GPU Optimized Docker Compose (v2.2.3)
# CUDA 11.8 + PyTorch 2.1.0 stable configuration - double free error resolved
# Encoding: UTF-8

services:
  # Main Whisper Application (GPU Optimized with Memory Protection)
  whisper-subtitles-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./data/models:/app/data/models
      - ./data/outputs:/app/data/outputs
      - ./data/logs:/app/data/logs
      - ./data/cache:/app/data/cache
      # GPU cache volumes for persistence
      - gpu_model_cache:/home/appuser/.cache/torch
      - gpu_huggingface_cache:/home/appuser/.cache/huggingface
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-8000}
      - DEBUG=${DEBUG:-false}
      # Memory-safe model configuration
      - WHISPER_MODEL=${WHISPER_MODEL:-large-v3}
      - LANGUAGE=${LANGUAGE:-auto}
      - SAMPLE_RATE=${SAMPLE_RATE:-16000}
      - CHUNK_SIZE=${CHUNK_SIZE:-1024}
      # CUDA 11.8 memory-safe settings
      - DEVICE=cuda
      - COMPUTE_TYPE=float16
      - BEAM_SIZE=${BEAM_SIZE:-5}
      - BEST_OF=${BEST_OF:-5}
      - TEMPERATURE=${TEMPERATURE:-0.0}
      - LENGTH_PENALTY=${LENGTH_PENALTY:-1.0}
      - PATIENCE=${PATIENCE:-1.0}
      # Memory-safe processing settings
      - ENABLE_WORD_TIMESTAMPS=${ENABLE_WORD_TIMESTAMPS:-true}
      - VAD_FILTER=${VAD_FILTER:-true}
      - COMPRESSION_RATIO_THRESHOLD=${COMPRESSION_RATIO_THRESHOLD:-2.4}
      - LOG_PROB_THRESHOLD=${LOG_PROB_THRESHOLD:--1.0}
      - NO_SPEECH_THRESHOLD=${NO_SPEECH_THRESHOLD:-0.6}
      # Conservative performance settings to prevent memory issues
      - MAX_WORKERS=${MAX_WORKERS:-2}
      - BATCH_SIZE=${BATCH_SIZE:-8}
      - MODEL_PATH=/app/data/models
      - OUTPUT_PATH=/app/data/outputs
      - LOG_PATH=/app/data/logs
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # API settings
      - RATE_LIMIT=${RATE_LIMIT:-100}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-100}
      - ENABLE_CORS=${ENABLE_CORS:-true}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      # Localization
      - TZ=${TZ:-Asia/Tokyo}
      - LANG=${LANG:-en_US.UTF-8}
      - LC_ALL=${LC_ALL:-en_US.UTF-8}
      # CUDA 11.8 memory-safe optimization
      - CUDA_VISIBLE_DEVICES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_CACHE_PATH=/tmp/cuda_cache
      - TORCH_CUDA_ARCH_LIST="7.0;7.5;8.0;8.6;8.9"
      # Memory protection - CRITICAL for double free prevention
      - CUDA_MEMORY_FRACTION=${CUDA_MEMORY_FRACTION:-0.8}
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128,expandable_segments:True
      - CUDA_MODULE_LOADING=LAZY
      - TORCH_CUDNN_V8_API_ENABLED=1
      # jemalloc memory allocator protection
      - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
      - MALLOC_CONF="dirty_decay_ms:1000,muzzy_decay_ms:1000"
      # Numba complete disabling - CRITICAL
      - NUMBA_DISABLE_JIT=1
      - NUMBA_CACHE_DIR=/dev/null
      - NUMBA_THREADING_LAYER=workqueue
      - NUMBA_PARALLEL=0
      - NUMBA_DISABLE_PERFORMANCE_WARNINGS=1
      - NUMBA_DISABLE_CUDA=1
      # Python memory management
      - PYTHONHASHSEED=0
      - PYTHONMALLOC=malloc
    networks:
      - whisper-network
    depends_on:
      - redis
    # GPU configuration with memory limits
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 8G  # Conservative memory limit for stability
    # Runtime configuration for older Docker versions
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 240s  # Extended startup time for memory-safe initialization

  # Redis for caching and session storage (memory-optimized)
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - whisper-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # GPU monitoring (optional, memory-safe)
  nvidia-smi-exporter:
    image: mindprince/nvidia_gpu_prometheus_exporter:0.1
    restart: unless-stopped
    ports:
      - "9835:9835"
    volumes:
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so:ro
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:ro
    networks:
      - whisper-network
    profiles:
      - monitoring
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 256M

  # Prometheus for monitoring (optional)
  prometheus:
    image: prom/prometheus:v2.49.0
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - whisper-network
    profiles:
      - monitoring
    deploy:
      resources:
        limits:
          memory: 1G

  # Grafana for visualization (optional)
  grafana:
    image: grafana/grafana:10.3.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - whisper-network
    depends_on:
      - prometheus
    profiles:
      - monitoring
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  gpu_model_cache:
    driver: local
  gpu_huggingface_cache:
    driver: local

networks:
  whisper-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16